WebPortalStudent/Controllers/NewsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.View;
using System.Reflection.Metadata.Ecma335;
using WebPortalStudent.Lib;
using WebPortalStudent.Models;
using WebPortalStudent.Services;

namespace WebPortalStudent.Controllers
{
    public class NewsController : BaseController<NewsController>
    {
        private readonly IS_News _news;
        private readonly IS_NewsCategory _newsCategory;

        public NewsController(IS_News news, IS_NewsCategory newsCategory)
        {
            _news = news;
            _newsCategory = newsCategory;
        }

        public async Task<IActionResult> Index(int category)
        {
            ResponseData<List<M_News>> res = new ResponseData<List<M_News>>();
            string mess;
            if (category == 0)
            {
                res = await _news.getListNews(_accessToken);
                mess = "Tất cả tin";
            }
            else
            {
                res = await _news.getListNewsByCategoryId(_accessToken, category);
                var datas = (await _newsCategory.getNewsCategoryById(_accessToken, category)).data;
                mess = datas.Name;
            }
            var resNewCategory = (ResponseData<List<M_NewsCategory>>)_memoryCache.Get("news_category_menu");
            ViewBag.dataNewsCategory = resNewCategory.data;
            ViewBag.dataNews = res.data;
            ViewBag.Name = mess;
            return View();
        }
        public async Task<IActionResult> Detail(string titleSlug, int id)
        {
            var res = await _news.getNewsById(_accessToken, id);
            if (res.result != 1 || res.data == null)
                return RedirectToAction("Index","Error");

            var resListNewData = await _news.getListNewsByCategoryId(_accessToken, res.data.newscategoryid.Value);
            var resNewCategory = (ResponseData<List<M_NewsCategory>>)_memoryCache.Get("news_category_menu");
            ViewBag.dataNewsCategory = resNewCategory.data;
            ViewBag.resListNewData = resListNewData.data;
            ViewBag.resNewData = res.data;
            return View();
        }
    }
}

WebPortalStudent/Controllers/TeacherController.cs
using Microsoft.AspNetCore.Mvc;
using System.Drawing.Printing;
using System.Net.WebSockets;
using WebPortalStudent.Models;
using WebPortalStudent.Services;

namespace WebPortalStudent.Controllers
{
    public class TeacherController : BaseController<TeacherController>
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IS_TeacherSubject _teachersubject;
        private readonly IS_Grade _grade;

        public TeacherController(ILogger<HomeController> logger, IS_TeacherSubject teachersubject, IS_Grade grade)
        {
            _logger = logger;
            _teachersubject = teachersubject;
            _grade = grade;
        }

        public async Task<IActionResult> Index()
        {
            var res = await _teachersubject.getListTeacherSubject(_accessToken);
            ViewBag.data = res.data;
            return View();
        }
        public async Task<IActionResult>Grade()
        {
            var resGrade = await _grade.getListGrade(_accessToken);
            ViewBag.dataGrade=resGrade.data;
            
            return View();
        }
    }
}

WebPortalStudent/Views/Shared/P_Footer.cshtml
<footer class="footer-area">
    <div class="main-footer pt-85 pb-80">
        <div class="container">
            <div class="row">
                <div class="col-md-3">
                    <div class="footer-widget">
                        <h3>THÔNG TIN KIDSCHOOL</h3>
                        <p>Chúng tôi sở hữu số lượng giảng viên, là chuyên gia trong nhiều lĩnh vực.</p>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="footer-widget">
                        <h3>classes section</h3>
                        <nav>
                            <ul>
                                <li><a href="#">Little Lambs</a></li>
                                <li><a href="#">master mind</a></li>
                                <li><a href="#">world round</a></li>
                                <li><a href="#">honter caves</a></li>
                            </ul>
                        </nav>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="footer-widget">
                        <h3>quick link</h3>
                        <nav>
                            <ul>
                                <li><a href="#">about us</a></li>
                                <li><a href="#">class keyword</a></li>
                                <li><a href="#">contact us</a></li>
                                <li><a href="#">shortcodes</a></li>
                            </ul>
                        </nav>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="footer-widget">
                        <h3>newsletter</h3>
                        <p>There are many variations of passages of Lorem Ipsum available, but the majority </p>
                        <form action="#" id="mc-form" class="mc-form fix">
                            <div class="subscribe-form">
                                <input id="mc-email" type="email" name="email" placeholder="Your Email">
                                <button id="mc-submit" type="submit">submit</button>
                            </div>
                        </form>
                        <div class="mailchimp-alerts text-centre fix text-small">
                            <div class="mailchimp-submitting"></div>
                            <div class="mailchimp-success"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="footer-bottom pt-12 pb-9">
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-sm-6 col-xs-12">
                    <p>
                        © 2022 <span class="text-capitalize">kidschool</span> Made
                        with <span style="color:#ea3a3c;">&#10084;</span> by
                        <a target="_blank" href="https://hasthemes.com/">HasThemes</a>
                    </p>
                </div>
                <div class="col-md-6 col-sm-6 col-xs-12">
                    <div class="footer-icons">
                        <ul>
                            <li><a href="https://www.facebook.com/"><i class="fa fa-facebook"></i></a></li>
                            <li><a href="https://twitter.com/"><i class="fa fa-twitter"></i></a></li>\
                            <li><a href="https://www.pinterest.com/"><i class="fa fa-pinterest"></i></a></li>
                            <li><a href="https://www.youtube.com/"><i class="fa fa-youtube"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>

WebPortalStudent/Views/Shared/P_Header.cshtml
@{
    var dataNewscategory = ViewBag.Newscategory as IEnumerable<M_NewsCategory>;
}
@section Styles{
    <link href="~/css/site.css" rel="stylesheet" asp-append-version="true" />
}
@section Scripts{
    <script src="~/js/site.js" asp-append-version="true"></script>
}
<header class="header-area sticker" id="topnav">
    <div class="header-wrapper header-padding">
        <div class="header-top hidden-xs">
            <div class="container">
                <div class="row">
                    <div class="col-sm-6">
                        <div class="top-left">
                            <ul>
                                <li><i class="icofont icofont-ui-call"></i>0123456789</li>
                                <li><i class="icofont icofont-ui-clock"></i> Thứ hai đến thứ bảy: 8.00 - 12.00</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="main-header">
            <div class="container">
                <div class="row">
                    <div class="col-md-3">
                        <div class="logo">
                            <a href="index.html">
                                <img src="~/assets/images/logo/logo.png" alt="kidschool">
                            </a>
                        </div>
                    </div>
                    <div class="col-md-9">
                        <div class="content-wrapper">
                            <div class="main-menu text-right">
                                <nav>
                                    <ul class="navigation-menu menu">
                                        <li>
                                            <a asp-controller="Home" asp-action="Index">TRANG CHỦ </a>
                                        </li>
                                        <li class="hidden-sm">
                                            <a asp-controller="Teacher" asp-action="Index">GIẢNG VIÊN</a>
                                        </li>
                                        <li class="hidden-sm">
                                            <a asp-controller="Teacher" asp-action="Grade" asp-route-id=0 asp-route-name=" ">LỚP HỌC</a>
                                        </li>
                                        <li>
                                            <div class="dropdown">
                                                <a class="dropdown-toggle" href="#" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                    TIN TỨC
                                                </a>
                                                <div class="dropdown-menu " aria-labelledby="dropdownMenuButton" style=" background-color: #F1F1F1 !important; width: 250px; padding-left: 60px">

                                                    <a class="dropdown-item w-100 " asp-controller="News" asp-action="Index" style="font-size: 20px; padding: 10px 10px;">Tin mới</a>
                                                    @if (dataNewscategory != null)
                                                    {
                                                        @foreach (var items in dataNewscategory)
                                                        {
                                                            <a class="dropdown-item w-100 mr-5" asp-controller="News" asp-action="Index" asp-route-category="@items.Id" style="font-size:20px; padding:10px 10px;">@items.Name</a>
                                                        }
                                                    }
                                                </div>
                                            </div>
                                        </li>

                                    </ul>
                                </nav>
                            </div>
                            <div class="mobile-menu hidden-lg hidden-md hidden-sm"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>

WebPortalStudent/Views/Shared/_Layout.cshtml
<!doctype html>
<html class="no-js" lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>@ViewData["Title"] || Kidschool</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" type="image/x-icon" href="~/assets/images/favicon.ico">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Sriracha&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lemonada&display=swap" rel="stylesheet">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>

    <link rel="stylesheet" href="~/assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/assets/css/core.css">
    <link href="~/assets/css/style.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/assets/css/shortcode/shortcodes.css">
    <link rel="stylesheet" href="~/assets/css/plugins/hover.css">
    <link rel="stylesheet" href="~/assets/css/responsive.css">
    <link href="#" data-style="styles" rel="stylesheet" asp-append-version="true">

    <script src="~/assets/js/vendor/modernizr-2.8.3.min.js"></script>
    @await RenderSectionAsync("Styles", required: false)
</head>
<body>
    <div class="wrapper bg-white fix">
        <div class="bg-white">
            <partial name="P_Header" />
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
            <partial name="P_Footer" />
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.1/dist/jquery.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>


    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/assets/js/vendor/jquery-1.12.4.min.js"></script>
    <script src="~/assets/js/bootstrap.min.js"></script>
    <script src="~/assets/js/owl.carousel.min.js"></script>
    <script src="~/assets/js/jquery.meanmenu.js"></script>
    <script src="~/assets/js/isotope.pkgd.min.js"></script>
    <script src="~/assets/js/imagesloaded.pkgd.min.js"></script>
    <script src="~/assets/js/ajax-mail.js"></script>
    <script src="~/assets/js/jquery.ajaxchimp.min.js"></script>
    <script src="~/assets/js/plugins.js"></script>
    <script src="~/assets/js/jquery.magnific-popup.js"></script>
    <script src="~/assets/js/jquery.counterup.min.js"></script>
    <script src="~/assets/js/waypoints.min.js"></script>
    <script src="~/assets/js/main.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebPortalStudent/Views/Shared/_P_ScriptsTableAndFormBasic.cshtml
<partial name="_P_ValidationScripts" />
<script src="~/assets/libs/datatables.net/js/jquery.dataTables.min.js"></script>
<script src="~/assets/libs/datatables.net-bs4/js/dataTables.bootstrap4.min.js"></script>
<script src="~/assets/libs/datatables.net-responsive/js/dataTables.responsive.min.js"></script>
<script src="~/assets/libs/datatables.net-responsive-bs4/js/responsive.bootstrap4.min.js"></script>
<script src="~/assets/libs/datatables.net-buttons/js/dataTables.buttons.min.js"></script>
<script src="~/assets/libs/datatables.net-bs4/js/ColReorderWithResize.js"></script>
<script src="~/assets/libs/ladda/spin.min.js"></script>
<script src="~/assets/libs/ladda/ladda.min.js"></script>
<script src="~/assets/libs/sweetalert2/sweetalert2.min.js"></script>
<script src="~/assets/libs/bootstrap-maxlength/bootstrap-maxlength.min.js"></script>
<partial name="_P_ValidationScripts" />
<script>
    try {
        $.fn.dataTable.ext.errMode = 'none';//Disable warning dataTable
    } catch (err) {
        console.log("ERROR DataTable: " + err.message);
    }
</script>

WebPortalStudent/Views/Shared/_P_StylesTableAndFormBasic.cshtml
<link href="~/assets/libs/datatables.net-bs4/css/dataTables.bootstrap4.min.css" rel="stylesheet" type="text/css" />
<link href="~/assets/libs/datatables.net-select-bs4/css/select.bootstrap4.min.css" rel="stylesheet" type="text/css" />
<link href="~/assets/libs/datatables.net-responsive-bs4/css/responsive.bootstrap4.min.css" rel="stylesheet" type="text/css" />
<link href="~/assets/libs/datatables.net-buttons-bs4/css/buttons.bootstrap4.min.css" rel="stylesheet" type="text/css" />
<link href="~/assets/libs/datatables.net-select-bs4/css/select.bootstrap4.min.css" rel="stylesheet" type="text/css" />
<link href="~/assets/libs/ladda/ladda-themeless.min.css" rel="stylesheet" type="text/css" />
<link href="~/assets/libs/sweetalert2/sweetalert2.min.css" rel="stylesheet" />

WebPortalStudent/Views/Shared/_P_ValidationScripts.cshtml
<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>